version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database