CREATE TABLE IF NOT EXISTS USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    BIRTH_DATE DATETIME(9) NULL,
    GENDER VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    CREATION_DATE DATETIME(9) NULL,
    MODIFICATION_DATE DATETIME(9) NULL,
    TOKEN VARCHAR(255) NOT NULL
);