CREATE TABLE IF NOT EXISTS ANIMALS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    AGE INT NULL,
    TIME_UNIT VARCHAR(255) NULL,
    SPECIE VARCHAR(255) NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CREATION_DATE DATETIME(9) NULL,
    MODIFICATION_DATE DATETIME(9) NULL,
    STATUS VARCHAR(255) NOT NULL,
    SEX VARCHAR(255) NOT NULL,
    "SIZE" VARCHAR(255) NOT NULL,
    CASTRATED BOOLEAN NOT NULL,
    CREATED_BY_ID INT NOT NULL,
    CONSTRAINT FK_ANIMALS_CREATED_BY_ID_ID FOREIGN KEY (CREATED_BY_ID) REFERENCES USERS(ID) ON UPDATE RESTRICT
)