CREATE TABLE IF NOT EXISTS ANIMAL_TO_DEFICIENCY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ANIMAL_ID INT NOT NULL,
    ANIMAL_DEFICIENCY_ID INT NOT NULL,
    CONSTRAINT FK_ANIMAL_TO_DEFICIENCY_ANIMAL_ID_ID FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMALS(ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT FK_ANIMAL_TO_DEFICIENCY_ANIMAL_DEFICIENCY_ID_ID FOREIGN KEY (ANIMAL_DEFICIENCY_ID) REFERENCES ANIMAL_DEFICIENCY(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)