INSERT INTO ANIMAL_DEFICIENCY ("NAME") VALUES ('DEAFNESS');
INSERT INTO ANIMAL_DEFICIENCY ("NAME") VALUES ('PARALYSIS');
INSERT INTO ANIMAL_DEFICIENCY ("NAME") VALUES ('PARTIAL_BLINDNESS');
INSERT INTO ANIMAL_DEFICIENCY ("NAME") VALUES ('TOTAL_BLINDNESS');
INSERT INTO ANIMAL_DEFICIENCY ("NAME") VALUES ('AMPUTATED_LIMB');
INSERT INTO ANIMAL_DEFICIENCY ("NAME") VALUES ('OTHER');