CREATE TABLE IF NOT EXISTS ANIMAL_TO_ADOPTER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ANIMAL_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CONSTRAINT FK_ANIMAL_TO_ADOPTER_ANIMAL_ID FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMALS(ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT FK_ANIMAL_TO_ADOPTER_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

ALTER TABLE ANIMALS ADD ADOPTER_USER INT;