CREATE TABLE IF NOT EXISTS ANIMAL_IMAGES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PATH VARCHAR(255) NOT NULL,
    FORMAT VARCHAR(40) NULL,
    BYTES INT NOT NULL,
    "TIMESTAMP" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ANIMAL_ID INT NOT NULL,
    CONSTRAINT FK_ANIMAL_IMAGES_ANIMAL_ID FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMALS(ID) ON DELETE CASCADE ON UPDATE RESTRICT,
)